### ISSUE TITLE
Handle empty text elements / attributes

### ISSUE THREAD

**Issue by rainman110** [RlanderRISCSW/cpacs_tigl_gen#7]
The generator currently accepts empty elements / attributes, even if those elements / attributes are required by the schema.

We should change this to the following behavior:
 - If element optional and empty text: make optional\<element\> null
 - If element required and empty: throw exception

To test this behavior, make e.g. the parentUID element of the wing empty.

**Comment by dixxi** [comment]
I agree to your second constraint, required std::string elements should not be empty. But I think it should be handled the same way as required elements which are missing. Currently, an error message is logged in this case (cf. CodeGen.cpp:656). I would also prefer an exception here, because missing required elements cause the corresponding data members to be left uninitialized, potentially causing undefined behavior.

Regarding the first constraint, I would regard it as an error if the element (despite being optional) is empty. Simply because the presence of an element should depend on the presence of its XML tag, not its content.
